### ISSUE TITLE
Färgschema

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/shr2024#1]
Analysera befintlig webbplats, se över konkurrenter och trender (årets färger, och liknande). Referera till moodboarden. Se till att ha en ordentlig förståelse för 60:30:10-principen. Kontrollera a11y, kontrast och vilka toner av valde färger som skall användas.

**Comment by Ovan81** [comment]
https://coolors.co/palette/1b98e0-fffc31-6da34d-66462c
öppna color pallettet i länken för att få gradients på färgerna
