### ISSUE TITLE
 Hitta stock-bilder

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/shr2024#2]
Analysera befintlig webbsida samt konkurrenter och fundera på vad för slags bildspråk som används. Leta upp stock-foton och samla så att de finns tillgängliga under projektet, både till moodboards, som exempelbilder men också som bakgrundsbilder och liknande. Se till att upphovsrätten efterlevs!

Dessa behöver inte ligga nedladdade i ert repocitory, det räcker med länkar till dem.

**Comment by Donflamin** [comment]
Bilderna är egentligen bara deras egna och inte en massa stock-bilder. Det finns en möjlighet att vi kommer behöva en eller två stock bilder, men då är det för att utföra ett specifikt syfte, och vad det skulle kunna vara får vi reda på när vi bygger sidan. Svårt att avgöra just nu.
