### ISSUE TITLE
Skapa moodboard

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/shr2024#6]
Analysera befintlig webbplats samt konkurrenter. Vad är syftet med sidan? Vilken känsla vill förmedlas? Skapa en moodboard, antingen fysiskt eller digitalt.

**Comment by Ovan81** [comment]
![Image](https://github.com/tcstenungsund/shr2024/assets/114009951/5bd6435d-b923-4abf-b504-8fc827947d11)
